<<<<<<< Updated upstream
version: '3'
services:
  app:
    build:
      context: .
    command: bundle exec puma -C config/puma.rb

    volumes:
      - .:/contact_book_app
      - public-data:/contact_book_app/public
      - tmp-data:/contact_book_app/tmp
      - log-data:/contact_book_app/log
    networks:
      - contact_book_app-network
    depends_on:
      - db

  db:
<<<<<<< Updated upstream
    image: mysql2:0.4.4
=======
    image: mysql:5.6.51
>>>>>>> Stashed changes
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: contact_book_app_development
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - contact_book_app-network

  web:
    build:
      context: ./nginx_docker
    volumes:
      - public-data:/contact_book_app/public
      - tmp-data:/contact_book_app/tmp
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - contact_book_app-network

volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:

networks:
<<<<<<< Updated upstream
  fitO2-network:
=======
  contact_book_app-network:
>>>>>>> Stashed changes
    external: true
=======
version: '3.4'

services:
  app_base: &app_base
    build:
      context: .
      dockerfile: ./Dockerfile
    tmpfs:
      - /tmp

  app:
    <<: *app_base
    stdin_open: true
    tty: true
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails server -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app:cached
      - rails_cache:/app/tmp/cache
      - bundle:/bundle
      - node_modules:/app/node_modules
      - packs:/app/public/packs
    environment:
      - BOOTSNAP_CACHE_DIR=/bundle/bootsnap
      - WEBPACKER_DEV_SERVER_HOST=webpacker
      - RAILS_ENV=development
      - DATABASE_HOST=mysql
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - '3000:3000'

  webpacker:
    <<: *app_base
    command: ./bin/webpack-dev-server
    ports:
      - '3035:3035'
    volumes:
      - .:/app:cached
      - bundle:/bundle
      - node_modules:/app/node_modules
      - packs:/app/public/packs
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0

  mysql:
    image: mysql:5.7
    volumes:
      - ./containers/db:/etc/mysql/conf.d/
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - 3306

volumes:
  mysql:
  bundle:
  rails_cache:
  node_modules:
  packs:
>>>>>>> Stashed changes
