version: '3.4'

services:
  app_base: &app_base
    build:
      context: .
      dockerfile: ./Dockerfile
    tmpfs:
      - /tmp

  app:
    <<: *app_base
    stdin_open: true
    tty: true
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails server -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app:cached
      - rails_cache:/app/tmp/cache
      - bundle:/bundle
      - node_modules:/app/node_modules
      - packs:/app/public/packs
    environment:
      - BOOTSNAP_CACHE_DIR=/bundle/bootsnap
      - WEBPACKER_DEV_SERVER_HOST=webpacker
      - RAILS_ENV=development
      - DATABASE_HOST=mysql
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - '3000:3000'

  webpacker:
    <<: *app_base
    command: ./bin/webpack-dev-server
    ports:
      - '3035:3035'
    volumes:
      - .:/app:cached
      - bundle:/bundle
      - node_modules:/app/node_modules
      - packs:/app/public/packs
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0

  mysql:
    image: mysql:5.7
    volumes:
      - ./containers/db:/etc/mysql/conf.d/
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - 3306

volumes:
  mysql:
  bundle:
  rails_cache:
  node_modules:
  packs:
